### ISSUE TITLE
Content: Improve navigation/structure

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#214]
As the site started to grow, the left menu has become outdated and disorganised.

This is a draft of how the new menu can be structured, having in mind future sections and the content that is already available:

----
- Events
- Calls for papers

----
Products and applications
- Machine translation APIs
- Machine translation products
- Machine translation features
- CAT/TMS integrations
- Applications
- Human translation workflows

----
Organisations
- Companies, teams and research laboratories
- Community
- Associations

---
Languages

----
Research and building
- Approaches
- Concepts
- Customisation
- Tags and placeholders
- Multi-engine machine translation
- Quality
- Papers

----
- History
- People

----
- Contributing
- 🌍 About Machine Translate

**Comment by zouharvi** [comment]
I feel like Contributing could be a subsection to "About". Otherwise I don't currently have an opinion.

Related to that, I think the ToC in the About page is a bit redundant. Why have a "Quality", "Openness" and "Accessibility" links if they're all 1-2 sentence paragraphs that take up barely 1/3 of the screen? I'm probably biased but it gives me the look of a marketspeak boilerplate. :slightly_smiling_face:

**Comment by cefoo** [comment]
> I feel like Contributing could be a subsection to "About". Otherwise I don't currently have an opinion.

I think that the purpose of having Contributing as a top-level section is to make it more prominent, as readers who casually arrive to Machine Translate may not know that they are encouraged to work on the content.  The contributing workflow is introduced in the home page, but it's more probable that people arrive at the site via a link to a particular article, either because that article is promoted or because they googled it.

Maybe we can place the "Edit this article" footer in another part of each page to make this action clearer. What do you think, @zouharvi?

**Comment by randyscansani** [comment]
The structure looks ok to me!
Perhaps it will be easier to judge the section names once we'll know more or less which topic will end up each of them. For example, for now I find it hard to understand what would end up in machine translation features vs machine translation products.
One small thing: perhaps "quality" under "Research" should be more explicit (quality estimation? Quality evaluation? Both?) otherwise the title can be misleading.

**Comment by liashahnazaryan** [comment]
> Organisations
> 
> * Companies, teams and research laboratories
> * Community
> * Associations

I would suggest making this section something like I've shown below to make the listing more comprehensive. The company, team, and research laboratory subfields can even be subheadings when you click on Organizations and not appear in the menu. 

Network

- Organizations
   - Companies
   - Teams
   - Research laboratories
- Community
- Associations

**Comment by liashahnazaryan** [comment]
> * History
> * People

Also, this section can be just called About if I understand the contents correctly, cause everybody knows what to expect on the About page: it's about the history, people, vision, etc.

**Comment by lena-voita** [comment]
**That looks like a really good update!**
![image](https://user-images.githubusercontent.com/16096019/156455381-1a1ad22b-088c-46a2-ad11-980154d8790f.png)

## There are several things we might want to think about in more detail.
### 1. addressing target audience needs
![image](https://user-images.githubusercontent.com/16096019/156455550-1e847ecf-bd1d-4261-a5ae-eed950f283b2.png)

The resource we are building has to address some questions/problems - it is the answer to something. If what we are building is the answer, then what was the question/problem? Can we formulate this clearly as briefly as possible? This could be useful at least for us. We have a target audience in mind -> we have a clear understanding of what it is our target audience wants -> we make it clear to our target audience that we have exactly what they want.

So, the structure has to reflect the answer to the question.

E.g., in the current version, we start with "Products and applications" - this means we are aiming mostly for people who want to use MT models and not learn how they work; if we start from "Research and development", then focus would be different. I think the current structure of the main blocks works, but as a sanity check we need to explicitly state what it is we want and for whom.

### 2. tell a story by putting blocks in logical order; mirror the entry point
![image](https://user-images.githubusercontent.com/16096019/156456754-c20548dd-d9e9-47c2-8e10-752cba3e42aa.png)

It'd be nice if the order of the blocks had a logical order, and this order was clear to the target audience. E.g., in the current version, the underlying idea might be going from high-level applied stuff deeper and deeper: "Products and applications" - how to use an MT system for one's needs, then who's working on it, then for which languages, and the deepest part with how it all works and how to build your own system. Ideally, this order/story has to be somewhere on the front page - we have to have an entry point to the site which immediately attracts attention of the target audience and tells smth like "Hey, we have what you want right here".

### 3. logical order at all levels
![image](https://user-images.githubusercontent.com/16096019/156457551-2b64aaab-a264-4750-837a-7f06bd537311.png)

Would be nice if the subcategories inside each block also had an underlying story behind: they could go in the order of developing/discussing/unraveling the issue. 

E.g., for "Research and development" the order could be as follows: 
![image](https://user-images.githubusercontent.com/16096019/156457823-321de11b-6e94-43c5-843e-059a5cc8915c.png)

It shows a sequence of steps in their order: one has to first choose a model, then a dataset, then train the model, then evaluate, then do something fancy. It'll also help to see if we really need certain subsections or not. (I didn't put all the headers from the current nav in here - this is just an example and we have to think about this more).

Of course, for some sections this might more important/reasonable than for the others, e.g. while for "Research and development" the structure kind of wants to be there, for "Organizations" finding one could be a bit tricky. But we can try and think about it everywhere - maybe something will come to mind.

P.S. This are just the things I think it'll be helpful to think about. We can have a call and discuss all this or each of the things separately.

**Comment by cefoo** [comment]
> For example, for now I find it hard to understand what would end up in machine translation features vs machine translation products.

We currently have a [products page](https://machinetranslate.org/products) which will be within the Machine translation products directory.
I think the main idea behind this directory and the Research and building one below is to separate MT in the lab vs in the real world, so to speak.

> One small thing: perhaps "quality" under "Research" should be more explicit (quality estimation? Quality evaluation? Both?) otherwise the title can be misleading.

You're right. We currently have a [quality estimation](https://machinetranslate.org/quality-estimation) page, but we have issue #86 for Quality evaluation.
Definitely something to think about. Do you think we should have two quality-dedicated pages? Within the same directory? @randyscansani

**Comment by cefoo** [comment]
> > Organisations
> > 
> > * Companies, teams and research laboratories
> > * Community
> > * Associations
> 
> I would suggest making this section something like I've shown below to make the listing more comprehensive. The company, team, and research laboratory subfields can even be subheadings when you click on Organizations and not appear in the menu.
> 
> Network
> 
>     * Organizations
>       
>       * Companies
>       * Teams
>       * Research laboratories
> 
>     * Community
> 
>     * Associations

I think that the idea of having them in a same table/page is that sometimes there is no clear distinction between these different categories. Companies like Microsoft are businesses who have their research labs, for instance. I think borders can be fuzzy, and this is a way to solve that.

**Comment by cefoo** [comment]
> > * History
> > * People
> 
> Also, this section can be just called About if I understand the contents correctly, cause everybody knows what to expect on the About page: it's about the history, people, vision, etc.

That is exactly the reason why it's not under **About**, @liashahnazaryan. Under **About**, as you imply, one would expect the History of the project (machinetranslate.org in this case) and the people involved in the project (all of us, in this case).

However, what we want to add to this directory is:

- The history of machine translation (maybe a timeline)
- The people who made the technology mode forwards by their research or breakthroughs.

**Comment by randyscansani** [comment]
> > For example, for now I find it hard to understand what would end up in machine translation features vs machine translation products.
> 
> We currently have a [products page](https://machinetranslate.org/products) which will be within the Machine translation products directory. I think the main idea behind this directory and the Research and building one below is to separate MT in the lab vs in the real world, so to speak.
> 
> > One small thing: perhaps "quality" under "Research" should be more explicit (quality estimation? Quality evaluation? Both?) otherwise the title can be misleading.
> 
> You're right. We currently have a [quality estimation](https://machinetranslate.org/quality-estimation) page, but we have issue #86 for Quality evaluation. Definitely something to think about. Do you think we should have two quality-dedicated pages? Within the same directory? @randyscansani

Yes if it is quality evaluation and quality estimation, it would make sense to keep them separated imho :)

**Comment by bittlingmayer** [comment]
I agree with Lena's suggestion that there should be a logical story.  Ideally people can read it like a book.

She suggests:

1. Products
2. Orgs
3. Languages
4. Research and development

(And of course ephemeral stuff like events and calls for papers at the very top, and meta stuff like people, history, contributing and about at the very bottom.)

Assuming we're talking mainly about the language support in products, I would probably go for

1. Products
2. Languages
3. Orgs
4. Research and development

Or maybe Orgs belong below research and development, since like people and events (series, not instances), they're more meta?

The challenge here is that a flat sequence or directory is hard.

For example that there are both products and research for a language, and orgs that do research and orgs that do production...  Wikipedia categories are actually labels not directories, for this reason.

We can and will add labels too, but in the nav and directory structure we still have to make choices.  Generally I would prioritise production over research.

**Comment by cefoo** [comment]
Taking your comments in mind, we have improved the rearranged menu as follows:

---
(News)*
Events
Calls for papers

---

Products and applications

- Machine translation APIs
- Machine translation products
- Machine translation features
- CAT/TMS integrations
- Applications
- Human translation workflows

---

Languages

---

Building and research

- System types (or Modality or Input mode)
- Approaches
- Data
- Training
- Evaluation
- Customisation
- Quality estimation
- Speech

---

References**

- Papers
- People
- Organisations
    - Companies, teams and research laboratories
    - Community
    - Associations

---

Contributing
🌍 About Machine Translate

---

\* “News” is a section that we are planning for the future.
** By clicking on “References” in the menu, the reader would be taken to a page where machine translation history is described. Within that directory, we could have the sections I included above.

We are not sure about naming the directory “References”. Maybe “More” or “History” would be more appropriate. What do you think?

What do you think of the overall nav planning?  We are very interested in reading what you think about the lower level order ("Products and applications" and "Building and research").

All your comments are welcome! 😊

**Comment by lena-voita** [comment]
### I like the high-level categories!

If our primary target audience are the people who want to apply a translation service for their goals, then starting with Products makes lots of sense
Trio Products - Languages - Building & Research looks nice: only three clear themes and visually the first and last one being huge looks good (pleasant to an eye)
The underlying story is clear: “what is there” -> “for which languages” -> “how it works inside”

## Building & Research

Overall looks good! There are a couple of things to think about that might tweak the sections a bit.

### 1. The structure: separate basic things and extensions/variants/advanced stuff.

I think it’d be nice to keep the standard things separately from the rest and be clear about it. It’s easier for the reader: they first understand how the standard systems work and come to the ways of modifying this for their purpose. In the extensions part, I’d present things from the perspective of how they change the standard pipeline.

<img width="638" alt="research_structure" src="https://user-images.githubusercontent.com/16096019/160115211-5670c8bc-a1f3-46c2-a2a8-f8f6278181e9.png">

### 2. System types (or Modality or Input mode): the title

“System types” is ambiguous in this context: the types can be defined based on:
 - Number of languages: bilingual/multilingual
 - Presence of additional information in the input: standard/context-aware
 - Availability of the whole source or generating on-the-fly: standard vs simultaneous
 - Generation type: autoregressive/non-autoregressive; left-to-right or arbitrary order
 - MT system types: neural, smt, rule-based
 - By the usage of external resources: “pure” or with dictionaries, translation memories, etc
 - [insert your option]

 - 
In this sense, “Modality” is much better, but assuming we are writing this for people who don’t know the contents yet (hence, might not know the terminology), I’d go with something more straightforward. E.g. “input type”.

### 3. System types (or Modality or Input mode): the location 
Generally, I like the idea of starting from the input: for your goals, you start from the input and to the rest. But in this particular context, if we are primarily talking about standard (text-based) MT, we might want to consider having it after the main part. E.g., we tell the story about the standard MT and then say “Oh, by the way, you can also do something if your input is image (e.g., running ASR before etc.) or speech (running ASR before MT or speech-to-speech), etc.” We could name this section smth like “Modifications for input types”, “Differences for input types” - can think about it. Maybe just “Non-textual input”?

### 4. System types (or Modality or Input mode): should it absorb Speech?
If the first section is talking about modalities, maybe Speech could be just part of it; unless you are planning on making Speech one of the key sections.

### 5. Quality evaluation and Estimation separated by Customisation: do we want it?

In my mind, both Quality evaluation and Quality estimation are (1) talking about quality and just have different use cases, (2) part of the main conversation about MT and not extensions (e.g.Customisation contains extensions and is somewhat optional compared to e.g. QE). Therefore, I’d at least not split quality parts with something else, and potentially merge these two parts in one: “Quality”. Inside we’d start from the distinctions between evaluation and estimation, e.g. like on the picture. 

<img width="991" alt="quality" src="https://user-images.githubusercontent.com/16096019/160115193-bd67c408-fb81-4ce8-9f30-c0ea92a063b1.png">

Merging them might also be a good idea since when we add everything we want, we are very likely to end up with quite a long navigation; keeping Quality in one place would save us a bit of trouble.

### 6. Structure proposal

Taking into account everything above, the structure could be smth like this:
 - Approaches
 - Data
 - Training
 - Quality
 - Customisation
 - Other input types
 - Other settings

“Other settings” is to include the things I mentioned above: simultaneous MT, context-aware, multilingual, etc. Once we have a full list of the things we want to mention, we can think of a proper title for this section or make several of them if needed.

## Products & Applications

To be honest, I don’t have a clear understanding of all the things that are supposed to be in this section - it makes it hard coming up with a nice structure or understanding if the current one is good. 
### Would it be possible for someone to briefly describe the contents of each of these subsections? 
This would help me a lot!

One thing that catches the eye is this.
<img width="839" alt="products_applications" src="https://user-images.githubusercontent.com/16096019/160115166-44faebb4-9c58-4699-8f55-c0ab930cb902.png">

**Comment by bittlingmayer** [comment]
> Customisation contains extensions and is somewhat optional compared to e.g. QE

As of 2022, many people have built or bought custom MT or a BLEU score or human eval, and only a few have built or bought Quality Estimation (even generic).

So > 90% of those who use QE use custom MT (and < 1% of custom MT users use QE).

**Comment by bittlingmayer** [comment]
Where would frameworks like Marian or OpenNMT go?

**Comment by cefoo** [comment]
> ### Products & Applications
> To be honest, I don’t have a clear understanding of all the things that are supposed to be in this section - it makes it hard coming up with a nice structure or understanding if the current one is good.
> **Would it be possible for someone to briefly describe the contents of each of these subsections?**

Of course!

- **Machine translation APIs** - What are the main APIs in the market and what they offer (which is generally not the same as the website version of the same MT engine)
- **Machine translation products** - What are the main MT providers in the market and what they offer
- **Machine translation features** - Features that can affect MT output, which include locales, formality levels, tag handling, glossary-awareness, input correction, etc.
- **CAT/TMS integrations** - Machine translation capabilities of translation software, ie what MT provider can be used with Trados
- **Applications** - Real-life use of machine translation, ie in chat, in marketplaces, in gaming, etc. Mainly what we have [here](https://machinetranslate.org/applications).
- **Human translation workflows** - The human (translator) involvement level after MT has been applied to a text. Mainly what we have [here](https://machinetranslate.org/workflows).

**Comment by lena-voita** [comment]
> > Customisation contains extensions and is somewhat optional compared to e.g. QE
> 
> As of 2022, many people have built or bought custom MT or a BLEU score or human eval, and only a few have built or bought Quality Estimation (even generic).
> 
> So > 90% of those who use QE use custom MT (and < 1% of custom MT users use QE).
> 
> Maybe that should change.

Aaa, I see. Then maybe the current location of the QE subsection is ok as long as the story behind is clear. And in any case, we can still start both pages (Quality evaluation and QE) with the distinction between them. Looks like judgment call :)

**Comment by lena-voita** [comment]
> > ### Products & Applications
> * **Machine translation APIs** - What are the main APIs in the market and what they offer (which is generally not the same as the website version of the same MT engine)
> * **Machine translation products** - What are the main MT providers in the market and what they offer
> * **Machine translation features** - Features that can affect MT output, which include locales, formality levels, tag handling, glossary-awareness, input correction, etc.
> * **CAT/TMS integrations** - Machine translation capabilities of translation software, ie what MT provider can be used with Trados
> * **Applications** - Real-life use of machine translation, ie in chat, in marketplaces, in gaming, etc. Mainly what we have [here](https://machinetranslate.org/applications).
> * **Human translation workflows** - The human (translator) involvement level after MT has been applied to a text. Mainly what we have [here](https://machinetranslate.org/workflows).

Thank you, Cecilia!

## General Structure
From what I understand, the high-level things we are talking about here is in what way mt is used (applications), who is doing the products and what are the characteristics. From this perspective, do you think it might be better to start from Applications?

![image](https://user-images.githubusercontent.com/16096019/161839826-eb637593-a3e3-4093-a6c1-a37283fd122b.png)

## Order of APIs & products
Also, I don't have a clear feeling of the distinction between the first two sections (APIs and products) - what is more basic/important? If products is more general, maybe it'd be better to start with them and then come to APIs. But again, here I don't have a very good expertise.

## Title for "Machine translation products"
Do you think it would make sense to make the title more clear? Specify e.g. like "Providers and products"/"Providers & MT engines", put this section first and then come to the APIs (which, as you mentioned, are not always the same as web versions).

## Generally, making the titles more clear: remove "machine translation" and specify
In the section titles, we could potentially omit "machine translation" (since everything on the website is about MT is not stated otherwise) and make them more clear. E.g., in the descriptions you provided for the APIs and products we have a phrase "and what they offer" - do you think we could come up with a formal phrase for that? Nothing comes to mind :(

The same for features: without description, it might be not very clear. If there's a way to clarify this in place of words "machine translation", it'd be better.

**Comment by cefoo** [comment]
> Thank you, Cecilia!
:)

> (APIs and products) - what is more basic/important?
I think Products should come before APIs, as APIs in less inclusive (technically, not all MT providers offer APIs, although most do). Also, some Providers could offer more than just an API?

> we could potentially omit "machine translation"
Absolutely

> "and what they offer" - do you think we could come up with a formal phrase for that?
I can only think of "APIs and features/properties", but I fear we would be too repetitive.  Maybe we can just delete "machine translation".  Perhaps "Products" (or maybe "Systems" or "Engines") vs "APIs" are titles clear enough, as the overall website is ruled by the same principle: straightforward and practical information presented mainly in tables and lists.  (Somehow, the audience would know more or less what to expect?)
