### ISSUE TITLE
Rearrange files in the repo

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#237]
During the nav reordering, we relocated the articles by changing their front matter variables, instead of moving files to different directories. The reason behind it was that `git mv` dropped the article history.

There are several ways to fix this issue and tidy up the repo. Here are some:

https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history

**Comment by zouharvi** [comment]
The solutions seem to be based on rewriting the git history. @bittlingmayer is probably more skilled in this than I am, but any time I used anything `filter` related in git, I always messed up. Furthermore, it may be an issue with already 20 forks because then the forkw histories would diverge.

The contribution history is still preserved in git (though not *directly*) traceable to the new file. When deciding between accumulating technical debt or losing this direct traceability convenience, I think the latter is the least problematic.

**Comment by bittlingmayer** [comment]
We could do this when we do `git mv` for each file:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

That way they still show up as contributors to the file.
